print('Hello Ai24')

jfasd
fasjkfadsjf
asdfdskfdskfjdskajfksjdfkajsdfads
fdskjfjdskjfdsjfdskajfsdkjfsda
fasdkjfjsdkfjdskjfkdsajfads
fadskjadsf
adsfdsk

fjasdkfjsadklfjsa
fsdjkfjdskfjsadf
asdfjsdkfjsdkjfksdjfksjdfsad
fdsakafjsdkfljsdfasd
fjadskfj
fadsjkfjdskfds


fjkdsajfksladjfklasdjfsdkjfksdjfasdjfkadsjfksdj